try
{
    throw "Error occurred";
}
catch(ex)
{
    console.log(ex);
}